# Generated by Django 5.1 on 2025-03-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diciplinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diciplina', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=255)),
                ('carga_horaria', models.EmailField(max_length=255)),
            ],
        ),
    ]
