# Generated by Django 5.1 on 2025-03-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('sala', models.CharField(max_length=255)),
                ('capacidade', models.CharField(max_length=255)),
                ('reponsavel', models.CharField(max_length=255)),
                ('periodo', models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite'), ('S', 'Sábados')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('cruso', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('CAT', 'Curso de Aprendiizagem Tecnica'), ('CT', 'Curso Tecnico'), ('FIC', 'Formação Iniciada e Continuada'), ('CS', 'Cuso Superior')], max_length=3)),
                ('hora_aula', models.CharField(max_length=255)),
                ('sigla', models.CharField(max_length=255)),
            ],
        ),
    ]
