# Generated by Django 5.1.7 on 2025-04-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ni', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gestores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ni', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Manutentores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ni', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('gestor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('abertura', models.DateTimeField()),
                ('fechamento', models.DateTimeField()),
                ('status', models.CharField(max_length=255)),
                ('patrimonio', models.CharField(max_length=255)),
                ('ambiente', models.CharField(max_length=255)),
                ('manutentor', models.CharField(max_length=255)),
                ('responsavel', models.CharField(max_length=255)),
                ('prioridade', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ni', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('localizacao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Responsaveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ni', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
    ]
