# Generated by Django 5.1.7 on 2025-05-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambientes',
            name='sig',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sensores',
            name='mac_address',
            field=models.CharField(max_length=100),
        ),
    ]
